# Generated by Django 3.0.3 on 2020-03-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='grad_year',
            field=models.IntegerField(blank=True, default=2022),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
