# Generated by Django 3.0.3 on 2020-03-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOC', '0002_auto_20200301_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='grad_year',
            field=models.IntegerField(),
        ),
    ]
