# Generated by Django 3.0.3 on 2020-03-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOC', '0003_auto_20200301_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
